const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Behaviors.Turret,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Behaviors.custom,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Shape3D.Acts.SetZ,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareZ,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Sprite.Exps.Z,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Shape3D.Cnds.CompareZ,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Exps.Z,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.custom.Acts.PushOutSolidAngle,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.custom.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Shape3D.Cnds.CompareOpacity,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Acts.SetLayerScale
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Flash: 0},
	{Pin: 0},
	{ArmorFrame: 0},
	{MoveTo: 0},
	{Leprechaun: 0},
	{Coin: 0},
	{pixilframe: 0},
	{Spawn: 0},
	{Sine: 0},
	{PowerSpawner: 0},
	{Spawner: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{Border: 0},
	{LepreM1: 0},
	{LepreM2: 0},
	{Tween: 0},
	{MUSICBUTTON: 0},
	{R: 0},
	{rainbow: 0},
	{Rock: 0},
	{Trans: 0},
	{TiledBackground3: 0},
	{Title: 0},
	{Trans2: 0},
	{TiledBackground5: 0},
	{Trans3: 0},
	{Trans4: 0},
	{LineOfSight: 0},
	{LeprechaunPREFINAL: 0},
	{Trans5: 0},
	{Sprite: 0},
	{YOURSOUL: 0},
	{LGC: 0},
	{SystemTEXT: 0},
	{Audio: 0},
	{Sprite2: 0},
	{gamebyMD: 0},
	{fortheBGI: 0},
	{Video: 0},
	{DeveloperDialogue: 0},
	{VIRUSTextDialogue: 0},
	{Developer2: 0},
	{cp: 0},
	{viruZicon: 0},
	{bushsG: 0},
	{Score: 0},
	{StatsINFO: 0},
	{LeprechaunICON: 0},
	{DesktopGameText: 0},
	{Health: 0},
	{"8Direction": 0},
	{BoundTo: 0},
	{DevIDLE: 0},
	{Keyboard: 0},
	{DevHealth: 0},
	{Destroyed: 0},
	{BOSShealth: 0},
	{BOSSBarCase: 0},
	{BOSSDamageTaken: 0},
	{Mouse: 0},
	{Fade: 0},
	{viruZSprite: 0},
	{ViruZTEXt: 0},
	{uded: 0},
	{uwin: 0},
	{TiledBackground4: 0},
	{Rotate: 0},
	{Meteorite: 0},
	{BulletE: 0},
	{Sprite5: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{DevShip: 0},
	{PSfinish: 0},
	{PScamera: 0},
	{"30COUNTDOWNTEXT": 0},
	{Eshipstop: 0},
	{PScutsceneTRIGGER: 0},
	{PaperSpaceIcon: 0},
	{effect: 0},
	{Clouds: 0},
	{Sprite15: 0},
	{PepperSpawner: 0},
	{MonkeyShtSpawner: 0},
	{PortalSpawner: 0},
	{cups: 0},
	{LadySit: 0},
	{MonkeySit: 0},
	{RockerSit: 0},
	{MatchaSpawner: 0},
	{SHOPHOVER: 0},
	{Sprite17: 0},
	{PixilartApp2: 0},
	{Thealth: 0},
	{Turret: 0},
	{Pathfinding: 0},
	{CoffeeBerryBorer: 0},
	{Bullet: 0},
	{Sprite9: 0},
	{FreeSmokeFxPixel: 0},
	{BugPortal: 0},
	{Sprite3: 0},
	{crosshair: 0},
	{CameraBorder: 0},
	{antiVIRUSPROGRESS: 0},
	{Text: 0},
	{PROGRESSpercent: 0},
	{BlackScreen: 0},
	{Sprite4: 0},
	{BLACKFADE: 0},
	{BoomEffectShipDestroyed: 0},
	{avirusorb: 0},
	{health: 0},
	{SBicon: 0},
	{SKIP: 0},
	{CONTROLSicon: 0},
	{HOWTOPLAY: 0},
	{AdviceCroc: 0},
	{Arrow: 0},
	{Custom: 0},
	{Player: 0},
	{"3DCamera": 0},
	{Face: 0},
	{BulletsNUMBER: 0},
	{CANSHOOT: 0},
	{shoot: 0},
	{m4: 0},
	{Sprite7: 0},
	{aim: 0},
	{Sprite6: 0},
	{"3DShape": 0},
	{AdviceCrocSPACEBUTTON: 0},
	{CONTROLSTEXT: 0},
	{"3DShape2": 0},
	{"3DShape3": 0},
	{Background: 0},
	{Sprite8: 0},
	{PlayerBullet: 0},
	{"3DShape4": 0},
	{MovingPlatform: 0},
	{"3Drestart": 0},
	{Tramp: 0},
	{viruzminion: 0},
	{"3DShapeMINION": 0},
	{BOSSTRIGGER: 0},
	{MinnionsSpawn: 0},
	{ExplosionEffect3D: 0},
	{FreeSmokeFxPixelSECOND: 0},
	{DamageScreen: 0},
	{FPS_Player_Health_Text: 0},
	{FPSBullet: 0},
	{TiledBackground6: 0},
	{DevShipPREFINAL: 0},
	{devshipBULLET: 0},
	{spawn: 0},
	{ViruZ: 0},
	{viruzmoveto: 0},
	{AllyDialog: 0},
	{allymoveto1: 0},
	{allymoveto2: 0},
	{BULLET3d: 0},
	{Sprite10: 0},
	{"3DShape5": 0},
	{crosss: 0},
	{GAMETITLELOGO: 0},
	{tranit: 0},
	{LepreCoinCleared: 0},
	{PaperSpaceCleared: 0},
	{StarBugzCleared: 0},
	{SetTransition: 0},
	{STARTGAME: 0},
	{LepreCoinHealth: 0},
	{startPAPERSPACEgame: 0},
	{COUNTDOWN: 0},
	{startPAPERSPACEgame2: 0},
	{COUNTDOWN2: 0},
	{ANTIVIRUSPROGRESSvariable: 0},
	{percentage: 0},
	{Sensitivity: 0},
	{dz: 0},
	{Gravity: 0},
	{OnGround: 0},
	{JumpStrenght: 0},
	{Bullets: 0},
	{Magazines: 0},
	{EmptyMagazine: 0},
	{PlayerHeight: 0},
	{PlayerSpeed: 0},
	{MouseSence: 0},
	{FPS_Health: 0},
	{AttackBOSS: 0},
	{AttackBOSSCHOOSE: 0},
	{ViruZHealth: 0}
];

self.InstanceType = {
	ArmorFrame: class extends self.ISpriteInstance {},
	Leprechaun: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	pixilframe: class extends self.ISpriteInstance {},
	PowerSpawner: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Border: class extends self.ISpriteInstance {},
	LepreM1: class extends self.ISpriteInstance {},
	LepreM2: class extends self.ISpriteInstance {},
	MUSICBUTTON: class extends self.ISpriteInstance {},
	R: class extends self.ISpriteInstance {},
	rainbow: class extends self.ISpriteInstance {},
	Rock: class extends self.ISpriteInstance {},
	Trans: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteInstance {},
	Trans2: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Trans3: class extends self.ISpriteInstance {},
	Trans4: class extends self.ISpriteInstance {},
	LeprechaunPREFINAL: class extends self.ISpriteInstance {},
	Trans5: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	YOURSOUL: class extends self.ITextInstance {},
	LGC: class extends self.ISpriteInstance {},
	SystemTEXT: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	gamebyMD: class extends self.ITextInstance {},
	fortheBGI: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	DeveloperDialogue: class extends self.ITextInstance {},
	VIRUSTextDialogue: class extends self.ITextInstance {},
	Developer2: class extends self.ISpriteInstance {},
	cp: class extends self.ISpriteInstance {},
	viruZicon: class extends self.ISpriteInstance {},
	bushsG: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	StatsINFO: class extends self.ISpriteInstance {},
	LeprechaunICON: class extends self.ISpriteInstance {},
	DesktopGameText: class extends self.ITextInstance {},
	DevIDLE: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DevHealth: class extends self.ITextInstance {},
	Destroyed: class extends self.ISpriteInstance {},
	BOSShealth: class extends self.ISpriteInstance {},
	BOSSBarCase: class extends self.ISpriteInstance {},
	BOSSDamageTaken: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	viruZSprite: class extends self.ISpriteInstance {},
	ViruZTEXt: class extends self.ITextInstance {},
	uded: class extends self.ISpriteInstance {},
	uwin: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Meteorite: class extends self.ISpriteInstance {},
	BulletE: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	DevShip: class extends self.ISpriteInstance {},
	PSfinish: class extends self.ISpriteInstance {},
	PScamera: class extends self.ISpriteInstance {},
	_30COUNTDOWNTEXT: class extends self.ITextInstance {},
	Eshipstop: class extends self.ISpriteInstance {},
	PScutsceneTRIGGER: class extends self.ISpriteInstance {},
	PaperSpaceIcon: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	PepperSpawner: class extends self.ISpriteInstance {},
	MonkeyShtSpawner: class extends self.ISpriteInstance {},
	PortalSpawner: class extends self.ISpriteInstance {},
	cups: class extends self.ISpriteInstance {},
	LadySit: class extends self.ISpriteInstance {},
	MonkeySit: class extends self.ISpriteInstance {},
	RockerSit: class extends self.ISpriteInstance {},
	MatchaSpawner: class extends self.ISpriteInstance {},
	SHOPHOVER: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	PixilartApp2: class extends self.ISpriteInstance {},
	Turret: class extends self.ISpriteInstance {},
	CoffeeBerryBorer: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	FreeSmokeFxPixel: class extends self.ISpriteInstance {},
	BugPortal: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	crosshair: class extends self.ISpriteInstance {},
	CameraBorder: class extends self.ISpriteInstance {},
	antiVIRUSPROGRESS: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	PROGRESSpercent: class extends self.ITextInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BLACKFADE: class extends self.ISpriteInstance {},
	BoomEffectShipDestroyed: class extends self.ISpriteInstance {},
	avirusorb: class extends self.ISpriteInstance {},
	health: class extends self.ISpriteInstance {},
	SBicon: class extends self.ISpriteInstance {},
	SKIP: class extends self.ITextInstance {},
	CONTROLSicon: class extends self.ISpriteInstance {},
	HOWTOPLAY: class extends self.ISpriteInstance {},
	AdviceCroc: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Face: class extends self.ISpriteInstance {},
	BulletsNUMBER: class extends self.ITextInstance {},
	m4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	aim: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	AdviceCrocSPACEBUTTON: class extends self.ISpriteInstance {},
	CONTROLSTEXT: class extends self.ITextInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	Background: class extends self.I3DShapeInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.I3DShapeInstance {},
	_3DShape4: class extends self.I3DShapeInstance {},
	MovingPlatform: class extends self.I3DShapeInstance {},
	_3Drestart: class extends self.I3DShapeInstance {},
	Tramp: class extends self.I3DShapeInstance {},
	viruzminion: class extends self.ISpriteInstance {},
	_3DShapeMINION: class extends self.I3DShapeInstance {},
	BOSSTRIGGER: class extends self.ISpriteInstance {},
	MinnionsSpawn: class extends self.ISpriteInstance {},
	ExplosionEffect3D: class extends self.I3DShapeInstance {},
	FreeSmokeFxPixelSECOND: class extends self.ISpriteInstance {},
	DamageScreen: class extends self.ISpriteInstance {},
	FPS_Player_Health_Text: class extends self.ITextInstance {},
	FPSBullet: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	DevShipPREFINAL: class extends self.ISpriteInstance {},
	devshipBULLET: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	ViruZ: class extends self.ISpriteInstance {},
	viruzmoveto: class extends self.ISpriteInstance {},
	AllyDialog: class extends self.ITextInstance {},
	allymoveto1: class extends self.ISpriteInstance {},
	allymoveto2: class extends self.ISpriteInstance {},
	BULLET3d: class extends self.I3DShapeInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	_3DShape5: class extends self.I3DShapeInstance {},
	crosss: class extends self.ISpriteInstance {},
	GAMETITLELOGO: class extends self.ISpriteInstance {}
}